package daamky.client;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import lombok.Generated;

public final class iIIiiI_Class39 {
    public static final int I_field_49 = 100;
    public static final int i_field_49 = 101;
    public static final int II_field_49 = 102;
    public static final int Ii_field_49 = 103;
    public static final int iI_field_49 = 200;
    public static final int ii_field_49 = 201;
    public static final int III_field_49 = 202;
    public static final int IIi_field_49 = 203;
    public static final int IiI_field_49 = 204;
    public static final int Iii_field_49 = 205;
    public static final int iII_field_49 = 206;
    public static final int iIi_field_49 = 207;
    public static final int iiI_field_49 = 208;
    public static final int iii_field_49 = 226;
    public static final int IIII_field_49 = 300;
    public static final int IIIi_field_49 = 301;
    public static final int IIiI_field_49 = 302;
    public static final int IIii_field_49 = 303;
    public static final int IiII_field_49 = 304;
    public static final int IiIi_field_49 = 305;
    public static final int IiiI_field_49 = 306;
    public static final int Iiii_field_49 = 307;
    public static final int iIII_field_49 = 308;
    public static final int iIIi_field_49 = 400;
    public static final int iIiI_field_49 = 401;
    public static final int iIii_field_49 = 402;
    public static final int iiII_field_49 = 403;
    public static final int iiIi_field_49 = 404;
    public static final int iiiI_field_49 = 405;
    public static final int iiii_field_49 = 406;
    public static final int IIIII_field_49 = 407;
    public static final int IIIIi_field_49 = 408;
    public static final int IIIiI_field_49 = 409;
    public static final int IIIii_field_49 = 410;
    public static final int IIiII_field_49 = 411;
    public static final int IIiIi_field_49 = 412;
    public static final int IIiiI_field_49 = 413;
    public static final int IIiii_field_49 = 414;
    public static final int IiIII_field_49 = 415;
    public static final int IiIIi_field_49 = 416;
    public static final int IiIiI_field_49 = 417;
    public static final int IiIii_field_49 = 418;
    public static final int IiiII_field_49 = 421;
    public static final int IiiIi_field_49 = 422;
    public static final int IiiiI_field_49 = 423;
    public static final int Iiiii_field_49 = 424;
    public static final int iIIII_field_49 = 425;
    public static final int iIIIi_field_49 = 426;
    public static final int iIIiI_field_49 = 428;
    public static final int iIIii_field_49 = 429;
    public static final int iIiII_field_49 = 431;
    public static final int iIiIi_field_49 = 451;
    public static final int iIiiI_field_49 = 500;
    public static final int iIiii_field_49 = 501;
    public static final int iiIII_field_49 = 502;
    public static final int iiIIi_field_49 = 503;
    public static final int iiIiI_field_49 = 504;
    public static final int iiIii_field_49 = 505;
    public static final int iiiII_field_49 = 506;
    public static final int iiiIi_field_49 = 507;
    public static final int iiiiI_field_49 = 508;
    public static final int iiiii_field_49 = 510;
    public static final int IIIIII_field_49 = 511;
    public static final Map<Integer, String> I_field_a567c40b;

    @Generated
    private iIIiiI_Class39() {
        throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
    }

    static {
        HashMap<Integer, String> hashMap = new HashMap<Integer, String>();
        hashMap.put(100, "Continue");
        hashMap.put(101, "Switching Protocols");
        hashMap.put(102, "Processing");
        hashMap.put(103, "Early Hints");
        hashMap.put(200, "OK");
        hashMap.put(201, "Created");
        hashMap.put(202, "Accepted");
        hashMap.put(203, "Non-Authoritative Information");
        hashMap.put(204, "No Content");
        hashMap.put(205, "Reset Content");
        hashMap.put(206, "Partial Content");
        hashMap.put(207, "Multi-Status");
        hashMap.put(208, "Already Reported");
        hashMap.put(226, "IM Used");
        hashMap.put(300, "Multiple Choices");
        hashMap.put(301, "Moved Permanently");
        hashMap.put(302, "Moved Temporarily");
        hashMap.put(303, "See Other");
        hashMap.put(304, "Not Modified");
        hashMap.put(305, "Use Proxy");
        hashMap.put(306, "Unused");
        hashMap.put(307, "Temporary Redirect");
        hashMap.put(308, "Permanent Redirect");
        hashMap.put(400, "Bad Request");
        hashMap.put(401, "Unauthorized");
        hashMap.put(402, "Payment Required");
        hashMap.put(403, "Forbidden");
        hashMap.put(404, "Not Found");
        hashMap.put(405, "Method Not Allowed");
        hashMap.put(406, "Not Acceptable");
        hashMap.put(407, "Proxy Authentication Required");
        hashMap.put(408, "Request Timeout");
        hashMap.put(409, "Conflict");
        hashMap.put(410, "Gone");
        hashMap.put(411, "Length Required");
        hashMap.put(412, "Precondition Failed");
        hashMap.put(413, "Payload Too Large");
        hashMap.put(414, "URI Too Long");
        hashMap.put(415, "Unsupported Media Type");
        hashMap.put(416, "Range Not Satisfiable");
        hashMap.put(417, "Expectation Failed");
        hashMap.put(418, "I'm a teapot");
        hashMap.put(421, "Misdirected Request");
        hashMap.put(422, "Unprocessable Content");
        hashMap.put(423, "Locked");
        hashMap.put(424, "Failed Dependency");
        hashMap.put(425, "Too Early");
        hashMap.put(426, "Upgrade Required");
        hashMap.put(428, "Precondition Required");
        hashMap.put(429, "Too Many Requests");
        hashMap.put(431, "Request Header Fields Too Large");
        hashMap.put(451, "Unavailable For Legal Reasons");
        hashMap.put(500, "Internal Server Error");
        hashMap.put(501, "Not Implemented");
        hashMap.put(502, "Bad Gateway");
        hashMap.put(503, "Service Unavailable");
        hashMap.put(504, "Gateway Timeout");
        hashMap.put(505, "HTTP Version Not Supported");
        hashMap.put(506, "Variant Also Negotiates");
        hashMap.put(507, "Insufficient Storage");
        hashMap.put(508, "Loop Detected");
        hashMap.put(510, "Not Extended");
        hashMap.put(511, "Network Authentication Required");
        I_field_a567c40b = Collections.unmodifiableMap(hashMap);
    }
}

